#!/bin/bash

# Integrating 'jump' Command
eval "$(jump shell bash)"

# Bash Stuff
alias back='cd ..'

# Git Stuff
alias gs='git status'
alias gb='git branch'
alias gc='git commit'
alias ga='git add'
alias gp='git push'

# Docker Stuff
alias dc="docker-compose" 
alias dps="docker ps -a --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}'"
alias dx='docker rm -f `docker ps -qa`'
